Feature/reorgs alert severities
HathorNetwork/hathor-wallet-service-sync_daemon pull request #62
Opened 2022-08-19 20:38 UTC by luislhl

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-08-20 18:58 UTC, andreabadesso requested changes

2022-08-20 18:58 UTC, andreabadesso commented on src/utils.ts
> +function get_alert_severity_for_reorg_size(reorg_size: number) {
use `camelCase`

2022-08-22 17:17 UTC, luislhl commented on src/utils.ts
> +function get_alert_severity_for_reorg_size(reorg_size: number) {
Fixed

2022-08-22 17:18 UTC, andreabadesso approved these changes

2022-08-22 21:40 UTC, tuliomir approved these changes

2022-08-23 14:15 UTC, merged